mysite/api/urls.py
from django.urls import path, include
from rest_framework_nested import routers
from api.views import * 
from rest_framework_simplejwt.views import TokenRefreshView


router = routers.DefaultRouter()
router.register(r'posts', PostsViewSet, basename='posts')
router.register(r'users', UserViewSet)

# user routers, api call : /api/users/myaccount
userAccount_router = routers.NestedDefaultRouter( router, r'users', lookup = 'user')
userAccount_router.register( r'myaccount', MyAccountViewSet, basename='user-myAccount')

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('', include(userAccount_router.urls)),
    path('token/', MyTokenObtainPairView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view()),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
#from django.views.generic import TemplateView

urlpatterns = [
    # Not working yet
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.png")),),
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    
]

mysite/posts/urls.py
from django.urls import path
from django.shortcuts import get_object_or_404
from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),
    path('posts/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user'),
    path('myaccount/', views.MyAccountView.as_view(), name='myaccount'),
]

mysite/posts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from ckeditor.fields import RichTextField
from polymorphic.models import PolymorphicModel


def get_today_datetime():
    return timezone.now()


def get_in_hour_datetime():
    return timezone.now() + timezone.timedelta(hours=1)


def get_in_day_datetime():
    return timezone.now() + timezone.timedelta(days=1)


def get_in_week_datetime():
    return timezone.now() + timezone.timedelta(days=7)


class Post(PolymorphicModel):
    title = models.CharField(max_length=300, unique=True)
    tags = models.ManyToManyField('Tag', blank=True)
    description = models.TextField()
    comments = models.ManyToManyField('Comment', blank=True)
    poster = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    posted_date = models.DateTimeField(default=get_today_datetime)
    modified_date = models.DateTimeField(default=get_today_datetime)

    class Meta:
        ordering = ['-posted_date']

    def __str__(self):
        '''Gets string representation of the post object
        Format: <post.title>

        Returns:
            str string representation of the post
        '''
        return self.title


class BlogPost(Post):
    # Using a package for rich text fields, it outputs as HTML so use the safe filter in the template
    # https://django-ckeditor.readthedocs.io/en/latest/
    body = RichTextField()
    images = models.ManyToManyField('Image', blank=True)

    def get_post_type(self):
        return 'Blog'


class AlbumPost(Post):
    images = models.ManyToManyField('Image', blank=False)

    def get_post_type(self):
        return 'Album'


class VideoPost(Post):
    video = models.ForeignKey('Video', on_delete=models.CASCADE)

    def get_post_type(self):
        return 'Video'


class Image(models.Model):
    # This is a charfield as images should be directly uploaded to the server rather than handled by the measly server running this webapp
    # Simply saving the url of the image to be accessed later
    file_path = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    STATIC = 'C'
    SERVER = 'S'
    hosting_method_choices = [
        (STATIC, 'Static'),
        (SERVER, 'Server'),
    ]
    hosting_method = models.CharField(
        max_length=1,
        choices=hosting_method_choices,
        default=STATIC,
    )

    def __str__(self):
        '''Gets string representation of the image object
        Format: <image.filePath>

        Returns:
            str string representation of the image
        '''
        return self.file_path

    def get_host_type(self):
        '''Gets the type of host the image is on

        Returns:
            str type of host the image is on
        '''
        if self.hosting_method == 'C':
            return 'Static'
        else:
            return 'Server'


class Video(models.Model):
    # Need to improve the default so it is unique
    title = models.CharField(
        max_length=300, unique=True, default='Untitled Video')
    # This is a charfield as videos should be directly uploaded to the server rather than handled by the measly server running this webapp
    # Simply saving the url of the video to be accessed later
    file_path = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    YOUTUBE = 'Y'
    SERVER = 'S'
    hosting_method_choices = [
        (YOUTUBE, 'YouTube'),
        (SERVER, 'Server'),
    ]
    hosting_method = models.CharField(
        max_length=1,
        choices=hosting_method_choices,
        default=YOUTUBE,
    )

    def __str__(self):
        '''Gets string representation of the video object
        Format: <video.filePath>

        Returns:
            str string representation of the video
        '''
        return self.file_path
    
    def get_host_type(self):
        '''Gets the type of host the video is on

        Returns:
            str type of host the video is on
        '''
        if self.hosting_method == 'Y':
            return 'YouTube'
        else:
            return 'Server'

# Tag represents a classification tag for content


class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        '''Gets string representation of the tag object
        Format: <tag.name>

        Returns:
            str string representation of the tag
        '''
        return self.name

    def get_content_count(self):
        '''Gets number of content objects with the tag

        Returns:
            int number of content objects with the tag
        '''
        return len(Post.objects.filter(tags=self))

    def get_content(self):
        '''Gets content objects with the tag

        Returns:
            list list of content objects with the tag
        '''
        return Post.objects.filter(tags=self)


class Comment(models.Model):
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    body = models.TextField()
    posted_date = models.DateTimeField(default=get_today_datetime)
    modified_date = models.DateTimeField(default=get_today_datetime)

    def __str__(self):
        '''Gets string representation of the comment object
        Format: <comment.user>: <comment.body>

        Returns:
            str string representation of the comment
        '''
        return self.user + ": " + self.body


class CustomUser(AbstractUser):
    # Using a library for phone number, if you want the string representation use phone.as_e164
    # https://django-phonenumber-field.readthedocs.io/en/latest/
    phone = PhoneNumberField(null=False, blank=True, unique=True)
    interests = models.ManyToManyField(Tag, blank=True)
    profile_picture = models.ForeignKey(
        Image, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        '''Gets string representation of the custom user object
        Format: <customuser.username>

        Returns:
            str string representation of the custom user
        '''
        return self.username

mysite/posts/views.py
from django.http import HttpResponseNotFound
from django.shortcuts import get_object_or_404, render
from django.views import View
from itertools import chain
from .models import *


class PostIndexView(View):
    def get(self, request):
        """Returns HttpResponse containing index page listing all posts in order of posting

        Returns:
            HttpResponse: index.html with context: posts
        """
        # This doesnt work when theres no post objects in the db
        posts = list(chain(BlogPost.objects.filter(),
                     AlbumPost.objects.filter(), VideoPost.objects.filter()))
        context = {'posts': posts}
        return render(request, 'posts/index.html', context)


class DetailView(View):
    def get(self, request, pk):
        """Returns HttpResponse containing detail page listing:
        The relevant post's attributes
        The relevant post's comments

        Returns:
            HttpResponse: relevent post_detail.html with context: post, comments
        """
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        if post.get_post_type() == 'Blog':
            context = {
                'blogpost': post,
                'comments': post.comments.order_by('-posted_date')
            }
            return render(request, 'posts/blog_post_detail.html', context)
        elif post.get_post_type() == 'Album':
            context = {
                'albumpost': post,
                'comments': post.comments.order_by('-posted_date')
            }
            return render(request, 'posts/album_post_detail.html', context)
        elif post.get_post_type() == 'Video':
            context = {
                'videopost': post,
                'comments': post.comments.order_by('-posted_date')
            }
            return render(request, 'posts/video_post_detail.html', context)
        else:
            return HttpResponseNotFound('<h1>Page not found: invalid post type</h1>')


class UserDetailView(View):
    def get(self, request, pk):
        """Returns HttpResponse containing personal account page listing:
        The specified user's details

        Returns:
            HttpResponse: user_detail.html with context: user
        """
        context = {
            'user': get_object_or_404(CustomUser, pk=self.kwargs['pk']),
        }
        return render(request, 'posts/user_detail.html', context)


class MyAccountView(View):
    def get(self, request):
        """Returns HttpResponse containing the logged in user's personal account page listing:
        The user's details

        Returns:
            HttpResponse: my_account.html with context: user
        """
        # Fix this once authentication is implemented
        logged_in_user = 1
        context = {
            'user': get_object_or_404(CustomUser, pk=logged_in_user),
        }
        return render(request, 'posts/my_account.html', context)


class LoginView(View):
    def get(self, request):
        """Returns HttpResponse containing login page

        Returns:
            HttpResponse: login.html
        """
        return render(request, 'posts/login.html')

mysite/posts/templates/posts/album_post_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{{ albumpost.title }}</title>
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'favicon.png' %}"
    />
  </head>

  <body>
    <h1>{{ albumpost.title }}</h1>

    <!-- Make this work -->
    <div class="album-container">
      {% for image in albumpost.images.all %}
      <img src="{{ image.file_path }}" />
      {% endfor %}
    </div>

    <div class="description-container">
      <p>{{ albumpost.description }}</p>
    </div>
  </body>
</html>

mysite/posts/templates/posts/blog_post_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{{ blogpost.title }}</title>
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'favicon.png' %}"
    />
    <link rel="stylesheet" href="{% static 'css/blog_post_detail.css' %}" />
  </head>

  <body>
    <script src="{% static 'js/navbarScrollIndicator.js' %}"></script>
    <div class="header">
      <div class="site-title-container">
        <h1 class="logo">Zac Benattar's Blog</h1>
      </div>

      <div class="progress-container">
        <div class="progress-bar" id="myBar"></div>
      </div>
    </div>

    <div class="content">
      <div class="headline-image-container">
        <img
          class="headline-image"
          src="{% static 'images/Content-moderation-image.jpg' %}"
        />
        <div class="blog-title-block">
          <h4>{{ blogpost.title }}</h4>
        </div>
      </div>

      <div class="blogpost-text-body">
        {{ blogpost.body | safe | linebreaks }}
      </div>
    </div>
  </body>
</html>

mysite/posts/templates/posts/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Zac Benattar's Blog</title>
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'favicon.png' %}"
    />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  </head>

  <body>
    <h1>Posts</h1>

    <div class="posts">
      {% if posts %}
      <ul>
        {% for post in posts %} {% if post.get_post_type == 'Blog' %}
        <div class="post-container">
          <a class="post-title" href="{% url 'posts:detail' post.id %}">{{ post.title }}</a>
          <p class="post-description">
            {{ post.description|truncatechars:512 }}
          </p>
        </div>

        {% elif post.get_post_type == 'Album' %}
        <div class="post-container">
          <a class="post-title" href="{% url 'posts:detail' post.id %}">{{ post.title }}</a>
          <p class="post-description">
            {{ post.description|truncatechars:512 }}
          </p>
        </div>

        {% elif post.get_post_type == 'Video' %}
        <div class="post-container">
          <a class="post-title" href="{% url 'posts:detail' post.id %}">{{ post.title }}</a>
          <p class="post-description">
            {{ post.description|truncatechars:512 }}
          </p>
        </div>
        {% endif %} {% endfor %}
      </ul>
      {% else %}
      <p>No posts are available.</p>
      {% endif %}
    </div>
  </body>
</html>

mysite/posts/templates/posts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Zac Benattar's Blog</title>
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'favicon.png' %}"
    />
  </head>

  <body>
    Nothing to see here yet
  </body>
</html>

mysite/posts/templates/posts/people.html
{% load static %}
<!doctype html>
<html lang="en">

</html>

<head>
    <title>Project Management App</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}" />
</head>

<body>

    <h1>{{ project.name }}</h1>

    <h2>People</h2>
    
    <div>
        {% if members %}
        <ul>
            {% for member in members %}
            <li><a href="{% url 'users:detail' member.user.id %}">{{ member.user.username }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <p> No members are available.</p>
        {% endif %}
    </div>


</body>

</html>

mysite/posts/templates/posts/suggestions.html
{% load static %}
<!doctype html>
<html lang="en">

</html>

<head>
    <title>Project Management App</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}" />
</head>

<body>
    <h1>{{ project.name }}</h1>

    <h2>Recommendations</h2>

    <div>
        {% if recommendations %}
        <h3>{{ recommendations_count }} Potential Issues</h3>
        <ul>
            {% for recommendation in recommendations %}
            <li>
                <h3>Issue: {{ recommendation.name }}</h3>
                <p>Solution: {{ recommendation.description }}</p>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p> No recommendations are available.</p>
        {% endif %}
    </div>


</body>

</html>

mysite/posts/templates/posts/tasks.html
{% load static %}
<!doctype html>
<html lang="en">

</html>

<head>
    <title>Project Management App</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}" />
</head>

<body>
    <h1>{{ project.name }}</h1>

    <h2>Tasks</h2>

    <div>
        {% if tasks %}
        <h3>{{ tasks_count }} Tasks</h3>
        <ul>
            {% for task in tasks %}
            <li>
                <h3>Name: {{ task.name }}</h3>
                <p>Description: {{ task.description }}</p>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p> No tasks are available.</p>
        {% endif %}
    </div>


</body>

</html>

mysite/posts/templates/posts/video_post_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{{ videopost.title }}</title>
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'favicon.png' %}"
    />
  </head>

  <body>
    <link rel="stylesheet" href="{% static 'css/video_post_detail.css' %}" />
    <div class="header">
      <div class="site-title-container">
        <h1 class="logo">Zac Benattar's Blog</h1>
      </div>
    </div>

    <div class="content">
      <div class="video-title-container">
        <h1 class="headline">{{ videopost.title }}</h1>
      </div>

      <div class="video-container">
        {{ blogpost.body | safe | linebreaks }}
        <!-- Selection statements to determine hosting of the video, whether it be from a file server or youtube -->
        {% if videopost.video.hosting_method == 'Y' %}
        <iframe
          width="560"
          height="315"
          src="https://www.youtube.com/embed/{{videopost.video.file_path}}"
          frameborder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        ></iframe>

        {% elif videopost.video.hosting_method == 'S' %}
        <iframe
          width="560"
          height="315"
          src="{{videopost.video.file_path}}"
          frameborder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        ></iframe>

        {% else %}
        <!-- This is probably insecure, possbily exposing file paths of the server -->
        <p>
          Invalid video hosting method {{videopost.video.hosting_method}}
          specified for {{videopost.video.title}}.
        </p>
        {% endif %}
      </div>
      <div class="video-description-container">
        <p>{{ videopost.description }}</p>
      </div>
    </div>
  </body>
</html>